export enum ApplicationErrorCode {
  // start at code 600, and the other errors will increment in order
  UNAUTHORIZED = 600,
  USERNAME_ALREADY_EXISTS,
  INCORRECT_USERNAME_OR_PASSWORD,
  EMAIL_MUST_BE_CONFIRMED,
  INVALID_TOKEN,
  EXPIRED_TOKEN,
  EMAIL_ALREADY_EXISTS,
  INSUFFICIENT_FUNDS,
  UNABLE_TO_PERFORM_UNSTAKING_REQUEST,
}
